print('(True and False) yields:',   True and False)
print('(True and True) yields:',    True and True)
print('(False and True) yields:',   False and True)
print('(True or False) yields:',    True or False)
print('(False or True) yields:',    False or True)
print('(False or False) yields:',   False or False)
print('(not True) yields:',    not True)
print('(not False) yields:', not False)